import { Dimensions, StyleSheet } from "react-native";

const { width } = Dimensions.get("window");

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "#030712",
  },
  header: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingHorizontal: 16,
    paddingVertical: 16,
    backgroundColor: "#030712",
    borderBottomWidth: 1,
    borderBottomColor: "#1F2937",
  },
  headerButton: {
    padding: 4,
  },
  headerTitle: {
    fontSize: 18,
    fontWeight: "bold",
    color: "#fff",
  },
  content: {
    flex: 1,
  },
  heroSection: {
    backgroundColor: "#111827",
    paddingHorizontal: 20,
    paddingTop: 24,
    paddingBottom: 20,
    marginBottom: 2,
  },
  profileHeader: {
    flexDirection: "row",
    alignItems: "center",
    marginBottom: 24,
  },
  avatarContainer: {
    position: "relative",
    marginRight: 16,
  },
  largeEmoji: {
    fontSize: 80,
  },
  verifiedBadge: {
    position: "absolute",
    bottom: 0,
    right: 0,
    backgroundColor: "#111827",
    borderRadius: 14,
  },
  heroInfo: {
    flex: 1,
  },
  heroName: {
    fontSize: 24,
    fontWeight: "bold",
    color: "#fff",
    marginBottom: 4,
  },
  heroService: {
    fontSize: 16,
    color: "#9CA3AF",
    marginBottom: 8,
  },
  heroLocation: {
    flexDirection: "row",
    alignItems: "center",
    gap: 4,
    marginBottom: 8,
  },
  locationText: {
    fontSize: 14,
    color: "#9CA3AF",
  },
  availabilityContainer: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "#064E3B",
    paddingHorizontal: 10,
    paddingVertical: 6,
    borderRadius: 12,
    alignSelf: "flex-start",
    gap: 6,
  },
  availabilityDot: {
    width: 6,
    height: 6,
    backgroundColor: "#10B981",
    borderRadius: 3,
  },
  availabilityText: {
    fontSize: 12,
    color: "#6EE7B7",
    fontWeight: "600",
  },
  quickStatsGrid: {
    flexDirection: "row",
    gap: 12,
    marginBottom: 20,
  },
  quickStatCard: {
    flex: 1,
    backgroundColor: "#1F2937",
    borderRadius: 16,
    padding: 12,
    alignItems: "center",
  },
  quickStatValue: {
    fontSize: 18,
    fontWeight: "bold",
    color: "#fff",
    marginTop: 8,
    marginBottom: 2,
  },
  quickStatLabel: {
    fontSize: 11,
    color: "#9CA3AF",
  },
  rateSection: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    backgroundColor: "#1F2937",
    borderRadius: 16,
    padding: 16,
  },
  rateLeft: {
    flex: 1,
  },
  rateLabel: {
    fontSize: 13,
    color: "#9CA3AF",
    marginBottom: 4,
  },
  rateValue: {
    fontSize: 28,
    fontWeight: "bold",
    color: "#3B82F6",
  },
  hireButton: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    backgroundColor: "#2563EB",
    paddingHorizontal: 24,
    paddingVertical: 14,
    borderRadius: 14,
  },
  hireButtonText: {
    fontSize: 16,
    fontWeight: "bold",
    color: "#fff",
  },
  tabContainer: {
    flexDirection: "row",
    backgroundColor: "#111827",
    paddingHorizontal: 16,
    paddingVertical: 12,
    gap: 8,
  },
  tab: {
    flex: 1,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 6,
    paddingVertical: 12,
    borderRadius: 12,
    backgroundColor: "#1F2937",
  },
  tabActive: {
    backgroundColor: "#1E3A8A",
  },
  tabText: {
    fontSize: 13,
    fontWeight: "600",
    color: "#9CA3AF",
  },
  tabTextActive: {
    color: "#3B82F6",
  },
  portfolioSection: {
    paddingTop: 20,
    paddingHorizontal: 16,
  },
  sectionHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 16,
  },
  sectionTitle: {
    fontSize: 18,
    fontWeight: "bold",
    color: "#fff",
  },
  sectionCount: {
    fontSize: 13,
    color: "#9CA3AF",
  },
  portfolioGrid: {
    flexDirection: "row",
    gap: 12,
  },
  portfolioColumn: {
    flex: 1,
    gap: 12,
  },
  portfolioCard: {
    backgroundColor: "#111827",
    borderRadius: 16,
    borderWidth: 1,
    borderColor: "#1F2937",
    overflow: "hidden",
  },
  portfolioImage: {
    aspectRatio: 1,
    backgroundColor: "#1F2937",
    justifyContent: "center",
    alignItems: "center",
  },
  portfolioEmoji: {
    fontSize: 60,
  },
  portfolioInfo: {
    padding: 12,
  },
  portfolioTitle: {
    fontSize: 14,
    fontWeight: "600",
    color: "#fff",
    marginBottom: 6,
  },
  portfolioMeta: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
  },
  portfolioDate: {
    fontSize: 11,
    color: "#6B7280",
  },
  portfolioLikes: {
    flexDirection: "row",
    alignItems: "center",
    gap: 4,
  },
  portfolioLikeCount: {
    fontSize: 11,
    color: "#9CA3AF",
  },
  aboutSection: {
    paddingTop: 20,
  },
  section: {
    paddingHorizontal: 16,
    marginBottom: 24,
  },
  aboutText: {
    fontSize: 14,
    color: "#D1D5DB",
    lineHeight: 22,
  },
  skillsGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 8,
  },
  skillBadge: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "#1F2937",
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderRadius: 12,
    gap: 6,
  },
  skillText: {
    fontSize: 13,
    color: "#E5E7EB",
  },
  certCard: {
    flexDirection: "row",
    backgroundColor: "#111827",
    borderWidth: 1,
    borderColor: "#1F2937",
    borderRadius: 16,
    padding: 16,
    marginBottom: 12,
  },
  certIcon: {
    width: 48,
    height: 48,
    backgroundColor: "#1F2937",
    borderRadius: 12,
    justifyContent: "center",
    alignItems: "center",
    marginRight: 12,
  },
  certInfo: {
    flex: 1,
  },
  certHeader: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    marginBottom: 4,
  },
  certTitle: {
    fontSize: 15,
    fontWeight: "600",
    color: "#fff",
    flex: 1,
  },
  certIssuer: {
    fontSize: 13,
    color: "#9CA3AF",
    marginBottom: 2,
  },
  certYear: {
    fontSize: 12,
    color: "#6B7280",
  },
  languagesContainer: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 8,
  },
  languageBadge: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "#1F2937",
    paddingHorizontal: 14,
    paddingVertical: 10,
    borderRadius: 12,
    gap: 8,
  },
  languageText: {
    fontSize: 14,
    color: "#E5E7EB",
    fontWeight: "500",
  },
  infoGrid: {
    gap: 12,
  },
  infoItem: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "#111827",
    borderWidth: 1,
    borderColor: "#1F2937",
    borderRadius: 14,
    padding: 16,
    gap: 12,
  },
  infoContent: {
    flex: 1,
  },
  infoLabel: {
    fontSize: 12,
    color: "#9CA3AF",
    marginBottom: 4,
  },
  infoValue: {
    fontSize: 15,
    fontWeight: "600",
    color: "#fff",
  },
  reviewsSection: {
    paddingTop: 20,
  },
  ratingCard: {
    flexDirection: "row",
    backgroundColor: "#111827",
    borderRadius: 20,
    padding: 20,
    marginHorizontal: 16,
    marginBottom: 24,
    gap: 20,
  },
  ratingLeft: {
    alignItems: "center",
    paddingRight: 20,
    borderRightWidth: 1,
    borderRightColor: "#1F2937",
  },
  ratingNumber: {
    fontSize: 48,
    fontWeight: "bold",
    color: "#fff",
    marginBottom: 8,
  },
  stars: {
    flexDirection: "row",
    gap: 4,
    marginBottom: 8,
  },
  ratingCount: {
    fontSize: 12,
    color: "#9CA3AF",
  },
  ratingRight: {
    flex: 1,
    gap: 8,
  },
  ratingBar: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
  },
  ratingLabel: {
    fontSize: 12,
    color: "#9CA3AF",
    width: 32,
  },
  barContainer: {
    flex: 1,
    height: 6,
    backgroundColor: "#1F2937",
    borderRadius: 3,
    overflow: "hidden",
  },
  barFill: {
    height: "100%",
    backgroundColor: "#FBBF24",
    borderRadius: 3,
  },
  ratingPercent: {
    fontSize: 11,
    color: "#9CA3AF",
    width: 32,
    textAlign: "right",
  },
  reviewCard: {
    backgroundColor: "#111827",
    borderWidth: 1,
    borderColor: "#1F2937",
    borderRadius: 16,
    padding: 16,
    marginBottom: 12,
  },
  reviewHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "flex-start",
    marginBottom: 12,
  },
  reviewLeft: {
    flexDirection: "row",
    gap: 12,
    flex: 1,
  },
  reviewEmoji: {
    fontSize: 36,
  },
  reviewName: {
    fontSize: 15,
    fontWeight: "600",
    color: "#fff",
    marginBottom: 6,
  },
  reviewStars: {
    flexDirection: "row",
    gap: 2,
  },
  reviewDate: {
    fontSize: 12,
    color: "#6B7280",
  },
  reviewComment: {
    fontSize: 14,
    color: "#D1D5DB",
    lineHeight: 20,
    marginBottom: 12,
  },
  reviewFooter: {
    flexDirection: "row",
    alignItems: "center",
  },
  helpfulButton: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    paddingVertical: 6,
    paddingHorizontal: 12,
    backgroundColor: "#1F2937",
    borderRadius: 8,
  },
  helpfulText: {
    fontSize: 12,
    color: "#9CA3AF",
  },
  bottomBar: {
    position: "absolute",
    bottom: 0,
    left: 0,
    right: 0,
    backgroundColor: "#111827",
    borderTopWidth: 1,
    borderTopColor: "#1F2937",
    flexDirection: "row",
    alignItems: "center",
    paddingHorizontal: 16,
    paddingVertical: 12,
    gap: 12,
  },
  messageButton: {
    width: 56,
    height: 56,
    backgroundColor: "#1F2937",
    borderRadius: 14,
    justifyContent: "center",
    alignItems: "center",
  },
  callButton: {
    width: 56,
    height: 56,
    backgroundColor: "#1F2937",
    borderRadius: 14,
    justifyContent: "center",
    alignItems: "center",
  },
  bookButton: {
    flex: 1,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 8,
    backgroundColor: "#2563EB",
    paddingVertical: 16,
    borderRadius: 14,
  },
  bookButtonText: {
    fontSize: 16,
    fontWeight: "bold",
    color: "#fff",
  },
  modalOverlay: {
    flex: 1,
    backgroundColor: "rgba(0, 0, 0, 0.95)",
    justifyContent: "center",
    alignItems: "center",
  },
  modalClose: {
    position: "absolute",
    top: 60,
    right: 20,
    zIndex: 10,
    padding: 8,
  },
  modalImageContainer: {
    width: width * 0.9,
    aspectRatio: 1,
    backgroundColor: "#1F2937",
    borderRadius: 20,
    justifyContent: "center",
    alignItems: "center",
  },
  modalEmoji: {
    fontSize: 180,
  },
});
